config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  get '/about', to: 'static#about'

  devise_for :users,
              path: '',
              path_names: {
                sign_in: 'login',
                sign_out: 'logout',
                sign_up: 'register'
              }

  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  has_one :user, through: :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments, through: :posts
  # has_many :create_comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def index
    news_url = "https://newsapi.org/v1/articles?source=buzzfeed&sortBy=top&apiKey=37ec75348f274f9e8194bd52feeac028"
    response = HTTParty.get(news_url)
    @news_data = response

    @all_posts = current_user.posts
    # @new_post = Post.new #post isnt tagged to any user

    @new_post = current_user.posts.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    render html: 'show form to create new post'
  end

  def edit
    @current_post = Post.find(params[:id])
  end

  def create
    # allowing mass assignment
    # creating_post = post_params

    # creating_post = current_user.post.build
    # creating_post.title = params[:post][:title]

    Post.create(post_params)
    redirect_to posts_path
  end

  def update
    # render json: post_update_params
    updated_post = Post.find(params[:id])

    # updated_post.title = params[:post][:title]
    # updated_post.content = params[:post][:content]
    # updated_post.user_id = params[:post][:user_id]
    # updated_post.foo = params[:post][:foo]
    # updated_post.past = params[:post][:past]

    updated_post.update(post_update_params)

    redirect_to posts_path
    # render html: 'updated'
  end

  def destroy
    # Post.destroy(params[:id])

    deleted_post = Post.find(params[:id])
    deleted_post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title,:content, :user_id)
  end

  def post_update_params
    params.require(:post).permit(:title,:content)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    "Test"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ketchup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Title is:  <%= yield (:title) %></h1>

    <%= render "partials/nav" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <footer>

      <%= render "partials/nav" %>
      &copy Jerald Chua 2017
    </footer>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav>
  <ul>
    <li><%= link_to "Home", root_path %> </li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "My Posts", posts_path %></li>

    <% if current_user %>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
  </ul>
</nav>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post: #{@current_post.id}") %>

<%= form_for @current_post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>

  <%#= hidden_field_tag 'post[user_id]', 10%>
  <%= f.hidden_field :user_id %>

  <%= f.submit %>
<% end %>

<%= @current_post.inspect %>

app/views/posts/index.html.erb
<% provide(:title, "My Posts By: #{@current_user.name}") %>

<h2>News from API</h2>
<ul>
  <%= @news_data["articles"].each do |article| %>
<li>
  <h3><%= article['title']%></h3>
  <p><%= article['description']%></p>
</li>
<% end %>
</ul>


<h2>Create new post</h2>
<%= form_for @new_post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>

  <%= f.hidden_field :user_id %>

  <%= f.submit %>
<% end %>

<ul>
  <% @all_posts.each do |post| %>
    <% if post.id #check if post has id => exist in db %>
      <li>
        <h4><%= post.title %></h4>
        <p>
          <%= post.content %>
        </p>

        <%= link_to "view", post_path(post) %>
        <%= link_to "edit", edit_post_path(post) %>
        <%= link_to "delete", post_path(post), method: :delete %>
      </li>
    <% end %>
  <% end  %>
</ul>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<small>
  Author: <%= @post.user.name %> (<%= @post.created_at %>)
</small>
<p>
  <%= @post.content %>
</p>

<%= link_to "My posts", posts_path %>